USE DATABASE UTIL;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TASK UTIL.PUBLIC.DAILY_REFRESH_EXCLUDE
  WAREHOUSE = ETL_DEV_WH
  SCHEDULE = 'USING CRON 30 10 * * * America/New_York'
  COMMENT = 'Daily refresh excluding selected columns'
AS
  CALL UTIL.PUBLIC.RUN_REFRESH_EXCLUDE_BATCH();

-- Enable task
ALTER TASK UTIL.PUBLIC.DAILY_REFRESH_EXCLUDE RESUME;