SELECT
  DATABASE_NAME,
  SCHEMA_NAME,
  NAME,
  STATE,
  SCHEDULED_TIME,
  COMPLETED_TIME,
  ERROR_MESSAGE
FROM TABLE(
  INFORMATION_SCHEMA.TASK_HISTORY(
    SCHEDULED_TIME_RANGE_START => DATEADD('hour', -24, CURRENT_TIMESTAMP())
  )
)
WHERE DATABASE_NAME = 'UTIL'
  AND SCHEMA_NAME = 'PUBLIC'
  AND NAME = 'DAILY_REFRESH_EXCLUDE'
ORDER BY SCHEDULED_TIME DESC;