USE DATABASE UTIL;
USE SCHEMA PUBLIC;

CREATE OR REPLACE PROCEDURE UTIL.PUBLIC.RUN_REFRESH_EXCLUDE_BATCH()
RETURNS STRING
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS
$$
function exec(sql){ snowflake.createStatement({sqlText: sql}).execute(); }

exec(`CALL UTIL.PUBLIC.REFRESH_TABLES_EXCLUDE_COLUMN(
  'DNA','REPORTING',
  'WORKATO_DB','PUBLIC',
  ARRAY_CONSTRUCT('ACCOUNT_FEATURE_STORE','OPPORTUNITY'),
  PARSE_JSON('{
    "REPORTING.ACCOUNT_FEATURE_STORE": ["ACCOUNT_UTILIZATION_PERCENT"],
    "REPORTING.OPPORTUNITY": ["ACCOUNT_MANAGER","ACCOUNT_NAME","ETL_MODIFIED_TS"]
  }')
)`);

exec(`CALL UTIL.PUBLIC.REFRESH_TABLES_EXCLUDE_COLUMN(
  'DNA','REPORTING_PRODUCT',
  'WORKATO_DB','PUBLIC',
  ARRAY_CONSTRUCT(
    'ACTIVE_VOLUMES_DAILY',
    'CURRENT_FILER_METRICS',
    'CURRENT_FILER_METRICS_HISTORY',
    'DAILY_ACCOUNT_PRODUCT_UTILIZATION',
    'DAILY_PRODUCT_ADOPTION_EVENTLOG',
    'UTILIZATION_HISTORY_BY_VOLUME'
  ),
  PARSE_JSON('{
    "REPORTING_PRODUCT.ACTIVE_VOLUMES_DAILY": ["ACCOUNT_RECORD_TYPE","VOLUME_ENHANCED"],
    "REPORTING_PRODUCT.CURRENT_FILER_METRICS": ["IP_ADDRESS"],
    "REPORTING_PRODUCT.CURRENT_FILER_METRICS_HISTORY": ["IP_ADDRESS"],
    "REPORTING_PRODUCT.DAILY_ACCOUNT_PRODUCT_UTILIZATION": ["ACCOUNT_ACV","ACCOUNT_RECORD_TYPE","CURRENT_CUSTOMER"],
    "REPORTING_PRODUCT.DAILY_PRODUCT_ADOPTION_EVENTLOG": ["ACCOUNT_ACV"],
    "REPORTING_PRODUCT.UTILIZATION_HISTORY_BY_VOLUME": ["ETL_MODIFIED_TS"]
  }')
)`);

exec(`CALL UTIL.PUBLIC.REFRESH_TABLES_EXCLUDE_COLUMN(
  'DNA','INTERMEDIATE_JIRA',
  'WORKATO_DB','PUBLIC',
  ARRAY_CONSTRUCT('ISSUE'),
  PARSE_JSON('{
    "INTERMEDIATE_JIRA.ISSUE": [
      "ACV","AFFECTEDVERSIONSAGGREGATE","BUGZILLA_ID","BUSINESS_AREA","DEFERRAL",
      "DEFERRAL_COUNT","DEFERRED_FROM_VERSION","DUE_DATE","ENG_FOUND","ETL_MODIFIED_TS",
      "PLATFORM","PLATFORM_2","VOTES"
    ]
  }')
)`);

exec(`CALL UTIL.PUBLIC.REFRESH_TABLES_EXCLUDE_COLUMN(
  'DNA','REPORTING_CX',
  'WORKATO_DB','PUBLIC',
  ARRAY_CONSTRUCT('SUPPORT_CASE'),
  PARSE_JSON('{
    "REPORTING_CX.SUPPORT_CASE": ["ACCOUNT_ACV","ACCOUNT_NAME"]
  }')
)`);

return 'Batch refresh completed';
$$;